---
application:
  name: "vaccineindia"
  project: "vaccineindia"
  organization: "QoveryCommunity"
routers:
- name: "main-vaccineindia"
  routes:
  - application_name: "vaccineindia"
    paths:
    - "/*"
